// SPDX-License-Identifier: Apache-2.0
package __PACKAGE__.timeaccessibility
import android.content.Context
import android.os.Build
import android.os.Handler
import android.os.Looper
import io.github.muntashirakon.adb.AdbPairingRequiredException
import io.github.muntashirakon.adb.android.AdbMdns
import java.util.concurrent.*
import java.util.concurrent.atomic.AtomicInteger
import java.util.concurrent.atomic.AtomicReference

data class SystemAccessState(val isReady:Boolean,val detail:String)
data class SystemCommandOutcome(val isSuccess:Boolean,val detail:String)
object TimeLocalAdbController {
 private val executor=Executors.newSingleThreadExecutor(); private val readerExecutor=Executors.newCachedThreadPool(); private val mainHandler=Handler(Looper.getMainLooper()); @Volatile private var lastDetail="Системный доступ не подключён."
 fun state(context:Context):SystemAccessState { if(Build.VERSION.SDK_INT<Build.VERSION_CODES.R)return SystemAccessState(false,"Встроенный системный доступ требует Android 11 или новее."); val ping=TimeShellBridge.ping(context); if(ping.success&&ping.detail.contains("uid=2000")){TimeShellBridge.markActive(context);return SystemAccessState(true,"Системный сервис активен до перезагрузки телефона.")}; return SystemAccessState(false,lastDetail) }
 fun connect(context:Context,callback:(SystemCommandOutcome)->Unit){executor.execute{deliver(callback,ensureShellServer(context.applicationContext))}}
 fun pair(context:Context,pairingCode:String,callback:(SystemCommandOutcome)->Unit){executor.execute{val c=context.applicationContext;val code=pairingCode.trim();val o=when{Build.VERSION.SDK_INT<Build.VERSION_CODES.R->SystemCommandOutcome(false,"Беспроводная отладка с кодом сопряжения доступна с Android 11.");!code.matches(Regex("^\\d{6}$"))->SystemCommandOutcome(false,"Введите шестизначный код сопряжения.");else->pairInternal(c,code)};lastDetail=o.detail;deliver(callback,o)}}
 fun applyTime(context:Context,targetMillis:Long,callback:(SystemCommandOutcome)->Unit){executor.execute{val c=context.applicationContext;val a=ensureShellServer(c);if(!a.isSuccess){deliver(callback,a);return@execute};val r=TimeShellBridge.call(c,"SET_TIME",targetMillis.toString());val o=if(r.success)SystemCommandOutcome(true,"OK: автоматическое время выключено, системные часы установлены.")else SystemCommandOutcome(false,"Системный сервис не выполнил изменение времени: ${compact(r.detail)}");lastDetail=o.detail;deliver(callback,o)}}
 fun setAutomaticTime(context:Context,enabled:Boolean,callback:(SystemCommandOutcome)->Unit){executor.execute{val c=context.applicationContext;val a=ensureShellServer(c);if(!a.isSuccess){deliver(callback,a);return@execute};val r=TimeShellBridge.call(c,"AUTO_TIME",if(enabled)"1" else "0");val o=if(r.success)SystemCommandOutcome(true,"OK: автоматическая синхронизация времени ${if(enabled)"включена" else "выключена"}.")else SystemCommandOutcome(false,"Системный сервис не изменил синхронизацию времени: ${compact(r.detail)}");lastDetail=o.detail;deliver(callback,o)}}
 private fun pairInternal(context:Context,code:String):SystemCommandOutcome {val host=AtomicReference<String?>(null);val port=AtomicInteger(-1);val latch=CountDownLatch(1);val mdns=AdbMdns(context,AdbMdns.SERVICE_TYPE_TLS_PAIRING){h,p->h?.hostAddress?.let(host::set);port.set(p);latch.countDown()};mdns.start();try{if(!latch.await(30,TimeUnit.SECONDS))return SystemCommandOutcome(false,"Не найдено окно сопряжения. Откройте «Сопряжение устройства с помощью кода» и оставьте его открытым.")}catch(_:InterruptedException){Thread.currentThread().interrupt();return SystemCommandOutcome(false,"Поиск окна сопряжения прерван.")}finally{mdns.stop()};val h=host.get()?:return SystemCommandOutcome(false,"Не удалось определить адрес беспроводной отладки.");val p=port.get();if(p<=0)return SystemCommandOutcome(false,"Не удалось определить порт сопряжения.");return runCatching{val m=TimeLocalAdbConnectionManager.getInstance(context);if(m.isConnected)m.disconnect();if(!m.pair(h,p,code))SystemCommandOutcome(false,"Android отклонил код сопряжения. Проверьте код и повторите попытку.")else{val ok=runCatching{m.autoConnect(context,12000)}.getOrDefault(false)||m.isConnected;if(!ok)SystemCommandOutcome(false,"Сопряжение выполнено, но ADB-подключение не установлено.")else startShellServer(context,m)}}.getOrElse{SystemCommandOutcome(false,"Сопряжение не выполнено: ${it.message.orEmpty()}")}}
 private fun ensureShellServer(context:Context):SystemCommandOutcome {if(Build.VERSION.SDK_INT<Build.VERSION_CODES.R)return SystemCommandOutcome(false,"Встроенный системный доступ требует Android 11 или новее.");val r=TimeShellBridge.ping(context);if(r.success&&r.detail.contains("uid=2000")){TimeShellBridge.markActive(context);return SystemCommandOutcome(true,"Системный сервис активен до перезагрузки телефона.")};TimeShellBridge.markInactive(context);val o=runCatching{val m=TimeLocalAdbConnectionManager.getInstance(context);if(!m.isConnected){val ok=m.autoConnect(context,8000)||m.isConnected;if(!ok)return@runCatching SystemCommandOutcome(false,"Не удалось подключиться к беспроводной отладке для запуска системного сервиса.")};startShellServer(context,m)}.recover{if(it is AdbPairingRequiredException)SystemCommandOutcome(false,"Требуется однократное сопряжение с беспроводной отладкой.")else SystemCommandOutcome(false,"Системный сервис недоступен: ${it.message.orEmpty()}")}.getOrThrow();lastDetail=o.detail;return o}
 private fun startShellServer(context:Context,manager:TimeLocalAdbConnectionManager):SystemCommandOutcome {val pkg=context.packageName;val cls="$pkg.timeaccessibility.TimeShellServerEntry";val starter=context.applicationInfo.nativeLibraryDir+"/libtime_machine_starter.so";val token=TimeShellBridge.token(context);val port=TimeShellBridge.PORT;val cmd="OLD=${'$'}(pidof time_machine_shell); if [ -n \"${'$'}OLD\" ]; then kill ${'$'}OLD >/dev/null 2>&1; sleep 1; fi; APK=${'$'}(pm path $pkg | head -n 1 | cut -d: -f2); \"$starter\" --apk=\"${'$'}APK\" --class=\"$cls\" --name=time_machine_shell --token=\"$token\" --port=$port";val launch=runAdbShell(manager,cmd);if(launch.exitCode!=0||!launch.stdout.contains("STARTED"))return SystemCommandOutcome(false,"Не удалось запустить системный shell-сервис: ${compact(launch.describe())}");repeat(30){Thread.sleep(200);val ping=TimeShellBridge.ping(context);if(ping.success&&ping.detail.contains("uid=2000")){TimeShellBridge.markActive(context);runCatching{if(manager.isConnected)manager.disconnect()};return SystemCommandOutcome(true,"Системный сервис запущен. После перезапуска приложения повторное подключение не требуется.")}};return SystemCommandOutcome(false,"Системный процесс запущен, но локальный канал не открылся: ${compact(launch.stdout)}")}
 private fun runAdbShell(manager:TimeLocalAdbConnectionManager,command:String):CommandResult=runCatching{val marker="__TM_BOOT_${System.nanoTime()}__";val stream=manager.openStream("shell:$command; code=${'$'}?; echo $marker${'$'}code");val future=readerExecutor.submit<String>{stream.openInputStream().bufferedReader().use{it.readText()}};val raw=try{future.get(9,TimeUnit.SECONDS)}catch(_:Throwable){runCatching{stream.close()};future.cancel(true);return CommandResult(-1,"","тайм-аут запуска shell-сервиса")};runCatching{stream.close()};val i=raw.lastIndexOf(marker);if(i<0)return CommandResult(-1,raw.trim(),"ADB shell не вернул код завершения");val e=raw.substring(i+marker.length).trim().lineSequence().firstOrNull().orEmpty();CommandResult(e.toIntOrNull()?:-1,raw.substring(0,i).trim(),"")}.getOrElse{CommandResult(-1,"",it.message.orEmpty())}
 private fun compact(v:String)=v.replace(Regex("\\s+")," ").trim().take(500);private fun deliver(cb:(SystemCommandOutcome)->Unit,o:SystemCommandOutcome){mainHandler.post{cb(o)}};private data class CommandResult(val exitCode:Int,val stdout:String,val stderr:String){fun describe()="exit=$exitCode out=${stdout.trim()} err=${stderr.trim()}"}
}
