package __PACKAGE__.timeaccessibility

import android.util.Xml
import com.facebook.react.bridge.*
import org.json.*
import org.xmlpull.v1.XmlPullParser
import java.io.StringReader

class TimeControlModule(private val context:ReactApplicationContext):ReactContextBaseJavaModule(context){
 override fun getName()="TimeControl"
 @ReactMethod fun getStatus(p:Promise){val s=jsonToWritableMap(TimeCycleStore.status(context));val z=TimeShizukuController.state();s.putBoolean("isShizukuRunning",z.isRunning);s.putBoolean("isShizukuPermissionGranted",z.isPermissionGranted);p.resolve(s)}
 @ReactMethod fun requestShizukuPermission(p:Promise){val c=TimeShizukuController.state();if(!c.isRunning){p.reject("SHIZUKU_NOT_RUNNING","Сначала запустите Shizuku.");return};if(c.isPermissionGranted||TimeShizukuController.requestPermission())p.resolve(true) else p.resolve(false)}
 @ReactMethod fun setAutomaticTime(e:Boolean,p:Promise){if(TimeCycleStore.isRunning(context)){p.reject("CYCLE_RUNNING","Нельзя переключать синхронизацию во время цикла.");return};TimeShizukuController.setAutomaticTime(context,e){o->if(o.isSuccess){TimeCycleStore.setAutomaticTimeEnabled(context,e);TimeCycleStore.addEvent(context,o.detail);p.resolve(jsonToWritableMap(TimeCycleStore.status(context)))}else p.reject("AUTOMATIC_TIME_FAILED",o.detail)}}
 @ReactMethod fun applyTime(t:Double,p:Promise){if(TimeCycleStore.isRunning(context)){p.reject("CYCLE_RUNNING","Нельзя вручную менять время во время цикла.");return};TimeShizukuController.applyTime(context,t.toLong()){o->if(o.isSuccess){TimeCycleStore.setAutomaticTimeEnabled(context,false);TimeCycleStore.addEvent(context,o.detail);p.resolve(jsonToWritableMap(TimeCycleStore.status(context)))}else p.reject("APPLY_TIME_FAILED",o.detail)}}
 @ReactMethod fun getOpenApps(p:Promise){TimeShizukuController.listOpenApps(context){o->if(!o.isSuccess){p.reject("OPEN_APPS_FAILED",o.detail);return@listOpenApps};val a=Arguments.createArray();o.detail.removePrefix("OK:").lineSequence().map{it.trim()}.filter{it.isNotEmpty()}.distinct().forEach{line->val parts=line.split('\t',limit=2);val pkg=parts[0].trim();if(pkg.isNotEmpty()){val m=Arguments.createMap();m.putString("packageName",pkg);m.putString("label",applicationLabel(pkg));val ps=Arguments.createArray();parts.getOrNull(1).orEmpty().split(',').map{it.trim()}.filter{it.isNotEmpty()}.forEach{ps.pushString(it)};m.putArray("processNames",ps);a.pushMap(m)}};p.resolve(a)}}
 @ReactMethod fun inspectApp(pkg:String,p:Promise){TimeShizukuController.inspectApp(context,pkg){o->if(!o.isSuccess){p.reject("UI_INSPECTION_FAILED",o.detail);return@inspectApp};runCatching{parseUiHierarchy(o.detail.removePrefix("OK:").trimStart())}.onSuccess{p.resolve(it)}.onFailure{p.reject("UI_PARSE_FAILED",it.message,it)}}}
 @ReactMethod fun invokeElement(pkg:String,b:String,p:Promise){TimeShizukuController.invokeElement(context,pkg,b){o->if(o.isSuccess)p.resolve(true)else p.reject("UI_INVOKE_FAILED",o.detail)}}
 @ReactMethod fun diagnoseShizuku(pkg:String,p:Promise){if(!PACKAGE_PATTERN.matches(pkg)){p.reject("INVALID_PACKAGE","Некорректное имя пакета.");return};TimeShizukuController.diagnosePackage(context,pkg){o->if(o.isSuccess)p.resolve(o.detail.removePrefix("OK:").trimStart())else p.reject("SHIZUKU_DIAGNOSTICS_FAILED",o.detail)}}
 @ReactMethod fun inspectUnityRuntime(pkg:String,p:Promise){Thread{val r=UnityRuntimeBridge.snapshot(pkg);context.runOnUiQueueThread{p.resolve(jsonToWritableMap(r))}}.start()}
 @ReactMethod fun invokeUnityRuntimeButton(pkg:String,id:String,p:Promise){Thread{val r=UnityRuntimeBridge.invoke(pkg,id);context.runOnUiQueueThread{if(r.optBoolean("ok",false))p.resolve(true)else p.reject("UNITY_RUNTIME_INVOKE_FAILED",r.optString("message"))}}.start()}
 @ReactMethod fun startCycle(s:ReadableMap,p:Promise){runCatching{val start=s.getDouble("startAtMillis").toLong();val d=s.getInt("stepDays");val h=s.getInt("stepHours");val m=s.getInt("stepMinutes");val pause=s.getInt("pauseSeconds");val reps=s.getInt("repeatsPerSeries");val sp=s.getInt("seriesPauseSeconds");val series=s.getInt("totalSeries");val total=s.getInt("totalCycles");TimeCycleStore.saveAndStart(context,start,d,h,m,pause,reps,sp,series,total);TimeCycleForegroundService.start(context)}.onSuccess{p.resolve(jsonToWritableMap(TimeCycleStore.status(context)))}.onFailure{p.reject("START_FAILED",it.message,it)}}
 @ReactMethod fun stopCycle(p:Promise){TimeShizukuCycleRunner.stop();TimeCycleStore.stop(context);TimeCycleForegroundService.stop(context);p.resolve(jsonToWritableMap(TimeCycleStore.status(context)))}
 @ReactMethod fun clearEvents(p:Promise){TimeCycleStore.clearEvents(context);p.resolve(true)}
 @Suppress("DEPRECATION") private fun applicationLabel(pkg:String)=runCatching{val i=context.packageManager.getApplicationInfo(pkg,0);context.packageManager.getApplicationLabel(i).toString().ifBlank{pkg}}.getOrDefault(pkg)
 private fun parseUiHierarchy(xml:String):WritableArray{val r=Arguments.createArray();val parser=Xml.newPullParser();parser.setInput(StringReader(xml));var e=parser.eventType;var seq=0;while(e!=XmlPullParser.END_DOCUMENT){if(e==XmlPullParser.START_TAG&&parser.name=="node"){val item=Arguments.createMap();val attrs=Arguments.createMap();item.putInt("sequence",seq++);item.putInt("depth",(parser.depth-2).coerceAtLeast(0));for(i in 0 until parser.attributeCount){val n=parser.getAttributeName(i);val v=parser.getAttributeValue(i)?:"";attrs.putString(n,v);item.putString(n,v)};val name=sequenceOf(parser.getAttributeValue(null,"text").orEmpty(),parser.getAttributeValue(null,"content-desc").orEmpty(),parser.getAttributeValue(null,"resource-id").orEmpty().substringAfterLast('/'),parser.getAttributeValue(null,"class").orEmpty().substringAfterLast('.')).firstOrNull{it.isNotBlank()}?:"Элемент $seq";item.putString("name",name);item.putMap("attributes",attrs);r.pushMap(item)};e=parser.next()};return r}
 private fun jsonToWritableMap(v:JSONObject):WritableMap{val r=Arguments.createMap();val it=v.keys();while(it.hasNext()){val k=it.next();when(val x=v.opt(k)){null,JSONObject.NULL->r.putNull(k);is Boolean->r.putBoolean(k,x);is Int->r.putInt(k,x);is Long->r.putDouble(k,x.toDouble());is Double->r.putDouble(k,x);is String->r.putString(k,x);is JSONObject->r.putMap(k,jsonToWritableMap(x));is JSONArray->r.putArray(k,jsonToWritableArray(x));else->r.putString(k,x.toString())}};return r}
 private fun jsonToWritableArray(v:JSONArray):WritableArray{val r=Arguments.createArray();for(i in 0 until v.length()){when(val x=v.opt(i)){null,JSONObject.NULL->r.pushNull();is Boolean->r.pushBoolean(x);is Int->r.pushInt(x);is Double->r.pushDouble(x);is String->r.pushString(x);is JSONObject->r.pushMap(jsonToWritableMap(x));is JSONArray->r.pushArray(jsonToWritableArray(x));else->r.pushString(x.toString())}};return r}
 companion object{private val PACKAGE_PATTERN=Regex("^[A-Za-z0-9._]+$")}
}
