package __PACKAGE__.timeaccessibility
import kotlin.math.abs
class TimeShizukuUserService:ITimeShizukuService.Stub(){
 override fun applyTime(t:Long):String{val a=runCommand("settings put global auto_time 0");val b=runCommand("cmd alarm set-time $t");val c=if(b.exitCode==0)b else runCommand("date -s @${t/1000L}");val e=runCommand("date +%s");val now=e.stdout.trim().toLongOrNull()?.times(1000L);return if(a.exitCode==0&&c.exitCode==0&&now!=null&&abs(now-t)<=90000L)"OK: время установлено." else "ОШИБКА: ${c.describe()}"}
 override fun setAutomaticTime(e:Boolean):String{val x=if(e)"1" else "0";val r=runCommand("settings put global auto_time $x");return if(r.exitCode==0)"OK: синхронизация изменена." else "ОШИБКА: ${r.describe()}"}
 override fun listOpenApps():String{val a=runCommand("dumpsys activity activities");val ps=runCommand("ps -A -o NAME").stdout.lineSequence().map{it.trim()}.toList();val pkgs=linkedSetOf<String>();Regex("""u\d+\s+([A-Za-z0-9._]+)/""").let{p->a.stdout.lineSequence().forEach{p.find(it)?.groupValues?.getOrNull(1)?.let(pkgs::add)}};return "OK:\n"+pkgs.joinToString("\n"){p->p+"\t"+ps.filter{it==p||it.startsWith("$p:")}.joinToString(",")}}
 override fun inspectApp(p:String,r:String):String{return "ОШИБКА: UI inspection unchanged in V25 diagnostics build."}
 override fun invokeElement(p:String,b:String,r:String):String{return "ОШИБКА: UI invocation unavailable in diagnostics build."}
 override fun diagnosePackage(p:String):String{if(!SAFE.matches(p))return "ОШИБКА: пакет";val pid=runCommand("pidof '$p'").stdout.trim().split(Regex("\\s+")).firstOrNull{it.matches(Regex("\\d+"))}.orEmpty();val t=mutableListOf<Pair<String,String>>();t+="id" to "id";t+="getenforce" to "getenforce";t+="package-flags" to "dumpsys package '$p' | grep -iE 'debuggable|profileable|flags|privateFlags'";t+="package-dump" to "cmd package dump '$p' | grep -iE 'debuggable|profileable'";t+="run-as" to "run-as '$p' id";t+="meminfo" to "dumpsys meminfo '$p'";if(pid.isNotBlank()){t+="proc-maps" to "head -n 5 /proc/$pid/maps";t+="debuggerd" to "timeout 4 debuggerd -b $pid";t+="simpleperf-stat" to "timeout 5 simpleperf stat -p $pid --duration 1";t+="simpleperf-record" to "rm -f /data/local/tmp/tc_perf.data; timeout 5 simpleperf record -p $pid --duration 1 -o /data/local/tmp/tc_perf.data; ls -l /data/local/tmp/tc_perf.data; rm -f /data/local/tmp/tc_perf.data";t+="am-profile" to "rm -f /data/local/tmp/tc.trace; am profile start '$p' /data/local/tmp/tc.trace; sleep 1; am profile stop '$p'; ls -l /data/local/tmp/tc.trace; rm -f /data/local/tmp/tc.trace"};return buildString{append("V25 extended Shizuku diagnostics\npackage=").append(p).append("\npid=").append(if(pid.isBlank())"NOT_FOUND" else pid).append('\n');t.forEach{(n,c)->val x=runCommand(c);append("\n=== ").append(n).append(" ===\ncommand: ").append(c).append("\nexit: ").append(x.exitCode).append("\nstdout:\n").append(x.stdout.ifBlank{"<empty>"}.take(12000)).append("\nstderr:\n").append(x.stderr.ifBlank{"<empty>"}.take(4000)).append('\n')}}}
 override fun destroy(){}
 private fun runCommand(c:String)=runCatching{val p=Runtime.getRuntime().exec(arrayOf("sh","-c",c));val o=p.inputStream.bufferedReader().use{it.readText()};val e=p.errorStream.bufferedReader().use{it.readText()};CommandResult(p.waitFor(),o,e)}.getOrElse{CommandResult(-1,"",it.message.orEmpty())};private data class CommandResult(val exitCode:Int,val stdout:String,val stderr:String){fun describe()="exit=$exitCode out=${stdout.trim()} err=${stderr.trim()}"};companion object{private val SAFE=Regex("^[A-Za-z0-9._]+$")}
}
